<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE strokes [
<!ELEMENT strokes (keystroke+)>
<!ELEMENT keystroke (dec+,hex+)>
<!ELEMENT dec (#PCDATA)>
<!ELEMENT hex (#PCDATA)>

<!ATTLIST keystroke id CDATA #IMPLIED> 
]>

<strokes><keystroke id=" "><dec>32</dec><hex>0020</hex></keystroke>
<keystroke id="!"><dec>33</dec><hex>0021</hex></keystroke>
<keystroke id="&#34;"><dec>34</dec><hex>0022</hex></keystroke>
<keystroke id="#"><dec>35</dec><hex>0023</hex></keystroke>
<keystroke id="$"><dec>36</dec><hex>0024</hex></keystroke>
<keystroke id="%"><dec>37</dec><hex>0025</hex></keystroke>
<keystroke id="&amp;"><dec>38</dec><hex>0026</hex></keystroke>
    <keystroke id="'"><dec>39</dec><hex>0027</hex></keystroke>
    <keystroke id="("><dec>40</dec><hex>0028</hex></keystroke>
    <keystroke id=")"><dec>41</dec><hex>0029</hex></keystroke>
    <keystroke id="*"><dec>42</dec><hex>002A</hex></keystroke>
    <keystroke id="+"><dec>43</dec><hex>002B</hex></keystroke>
    <keystroke id=","><dec>44</dec><hex>002C</hex></keystroke>
    <keystroke id="-"><dec>45</dec><hex>002D</hex></keystroke>
    <keystroke id="."><dec>46</dec><hex>002E</hex></keystroke>
    <keystroke id="/"><dec>47</dec><hex>002F</hex></keystroke>
    <keystroke id="0"><dec>48</dec><hex>0030</hex></keystroke>
    <keystroke id="1"><dec>49</dec><hex>0031</hex></keystroke>
    <keystroke id="2"><dec>50</dec><hex>0032</hex></keystroke>
    <keystroke id="3"><dec>51</dec><hex>0033</hex></keystroke>
    <keystroke id="4"><dec>52</dec><hex>0034</hex></keystroke>
    <keystroke id="5"><dec>53</dec><hex>0035</hex></keystroke>
    <keystroke id="6"><dec>54</dec><hex>0036</hex></keystroke>
    <keystroke id="7"><dec>55</dec><hex>0037</hex></keystroke>
    <keystroke id="8"><dec>56</dec><hex>0038</hex></keystroke>
    <keystroke id="9"><dec>57</dec><hex>0039</hex></keystroke>
    <keystroke id=":"><dec>58</dec><hex>003A</hex></keystroke>
    <keystroke id=";"><dec>59</dec><hex>003B</hex></keystroke>
    <keystroke id="&lt;"><dec>60</dec><hex>003C</hex></keystroke>
    <keystroke id="="><dec>61</dec><hex>003D</hex></keystroke>
    <keystroke id=">"><dec>62</dec><hex>003E</hex></keystroke>
    <keystroke id="?"><dec>63</dec><hex>003F</hex></keystroke>
    <keystroke id="@"><dec>64</dec><hex>0040</hex></keystroke>
    <keystroke id="A"><dec>65</dec><hex>0041</hex></keystroke>
    <keystroke id="B"><dec>66</dec><hex>0042</hex></keystroke>
    <keystroke id="C"><dec>67</dec><hex>0043</hex></keystroke>
    <keystroke id="D"><dec>68</dec><hex>0044</hex></keystroke>
    <keystroke id="E"><dec>69</dec><hex>0045</hex></keystroke>
    <keystroke id="F"><dec>70</dec><hex>0046</hex></keystroke>
    <keystroke id="G"><dec>71</dec><hex>0047</hex></keystroke>
    <keystroke id="H"><dec>72</dec><hex>0048</hex></keystroke>
    <keystroke id="I"><dec>73</dec><hex>0049</hex></keystroke>
    <keystroke id="J"><dec>74</dec><hex>004A</hex></keystroke>
    <keystroke id="K"><dec>75</dec><hex>004B</hex></keystroke>
    <keystroke id="L"><dec>76</dec><hex>004C</hex></keystroke>
    <keystroke id="M"><dec>77</dec><hex>004D</hex></keystroke>
    <keystroke id="N"><dec>78</dec><hex>004E</hex></keystroke>
    <keystroke id="O"><dec>79</dec><hex>004F</hex></keystroke>
    <keystroke id="P"><dec>80</dec><hex>0050</hex></keystroke>
    <keystroke id="Q"><dec>81</dec><hex>0051</hex></keystroke>
    <keystroke id="R"><dec>82</dec><hex>0052</hex></keystroke>
    <keystroke id="S"><dec>83</dec><hex>0053</hex></keystroke>
    <keystroke id="T"><dec>84</dec><hex>0054</hex></keystroke>
    <keystroke id="U"><dec>85</dec><hex>0055</hex></keystroke>
    <keystroke id="V"><dec>86</dec><hex>0056</hex></keystroke>
    <keystroke id="W"><dec>87</dec><hex>0057</hex></keystroke>
    <keystroke id="X"><dec>88</dec><hex>0058</hex></keystroke>
    <keystroke id="Y"><dec>89</dec><hex>0059</hex></keystroke>
    <keystroke id="Z"><dec>90</dec><hex>005A</hex></keystroke>
    <keystroke id="["><dec>91</dec><hex>005B</hex></keystroke>
    <keystroke id="\"><dec>92</dec><hex>005C</hex></keystroke>
    <keystroke id="]"><dec>93</dec><hex>005D</hex></keystroke>
    <keystroke id="^"><dec>94</dec><hex>005E</hex></keystroke>
    <keystroke id="_"><dec>95</dec><hex>005F</hex></keystroke>
    <keystroke id="`"><dec>96</dec><hex>0060</hex></keystroke>
    <keystroke id="a"><dec>97</dec><hex>0061</hex></keystroke>
    <keystroke id="b"><dec>98</dec><hex>0062</hex></keystroke>
    <keystroke id="c"><dec>99</dec><hex>0063</hex></keystroke>
    <keystroke id="d"><dec>100</dec><hex>0064</hex></keystroke>
    <keystroke id="e"><dec>101</dec><hex>0065</hex></keystroke>
    <keystroke id="f"><dec>102</dec><hex>0066</hex></keystroke>
    <keystroke id="g"><dec>103</dec><hex>0067</hex></keystroke>
    <keystroke id="h"><dec>104</dec><hex>0068</hex></keystroke>
    <keystroke id="i"><dec>105</dec><hex>0069</hex></keystroke>
    <keystroke id="j"><dec>106</dec><hex>006A</hex></keystroke>
    <keystroke id="k"><dec>107</dec><hex>006B</hex></keystroke>
    <keystroke id="l"><dec>108</dec><hex>006C</hex></keystroke>
    <keystroke id="m"><dec>109</dec><hex>006D</hex></keystroke>
    <keystroke id="n"><dec>110</dec><hex>006E</hex></keystroke>
    <keystroke id="o"><dec>111</dec><hex>006F</hex></keystroke>
    <keystroke id="p"><dec>112</dec><hex>0070</hex></keystroke>
    <keystroke id="q"><dec>113</dec><hex>0071</hex></keystroke>
    <keystroke id="r"><dec>114</dec><hex>0072</hex></keystroke>
    <keystroke id="s"><dec>115</dec><hex>0073</hex></keystroke>
    <keystroke id="t"><dec>116</dec><hex>0074</hex></keystroke>
    <keystroke id="u"><dec>117</dec><hex>0075</hex></keystroke>
    <keystroke id="v"><dec>118</dec><hex>0076</hex></keystroke>
    <keystroke id="w"><dec>119</dec><hex>0077</hex></keystroke>
    <keystroke id="x"><dec>120</dec><hex>0078</hex></keystroke>
    <keystroke id="y"><dec>121</dec><hex>0079</hex></keystroke>
    <keystroke id="z"><dec>122</dec><hex>007A</hex></keystroke>
    <keystroke id="{"><dec>123</dec><hex>007B</hex></keystroke>
    <keystroke id="|"><dec>124</dec><hex>007C</hex></keystroke>
    <keystroke id="}"><dec>125</dec><hex>007D</hex></keystroke>
    <keystroke id="~"><dec>126</dec><hex>007E</hex></keystroke>
    <keystroke id=""><dec>127</dec><hex>007F</hex></keystroke>
    <keystroke id="€"><dec>128</dec><hex>0080</hex></keystroke>
    <keystroke id=""><dec>129</dec><hex>0081</hex></keystroke>
    <keystroke id="‚"><dec>130</dec><hex>0082</hex></keystroke>
    <keystroke id="ƒ"><dec>131</dec><hex>0083</hex></keystroke>
    <keystroke id="„"><dec>132</dec><hex>0084</hex></keystroke>
    <keystroke id="…"><dec>133</dec><hex>0085</hex></keystroke>
    <keystroke id="†"><dec>134</dec><hex>0086</hex></keystroke>
    <keystroke id="‡"><dec>135</dec><hex>0087</hex></keystroke>
    <keystroke id="ˆ"><dec>136</dec><hex>0088</hex></keystroke>
    <keystroke id="‰"><dec>137</dec><hex>0089</hex></keystroke>
    <keystroke id="Š"><dec>138</dec><hex>008A</hex></keystroke>
    <keystroke id="‹"><dec>139</dec><hex>008B</hex></keystroke>
    <keystroke id="Œ"><dec>140</dec><hex>008C</hex></keystroke>
    <keystroke id=""><dec>141</dec><hex>008D</hex></keystroke>
    <keystroke id="Ž"><dec>142</dec><hex>008E</hex></keystroke>
    <keystroke id=""><dec>143</dec><hex>008F</hex></keystroke>
    <keystroke id=""><dec>144</dec><hex>0090</hex></keystroke>
    <keystroke id="‘"><dec>145</dec><hex>0091</hex></keystroke>
    <keystroke id="’"><dec>146</dec><hex>0092</hex></keystroke>
    <keystroke id="“"><dec>147</dec><hex>0093</hex></keystroke>
    <keystroke id="”"><dec>148</dec><hex>0094</hex></keystroke>
    <keystroke id="•"><dec>149</dec><hex>0095</hex></keystroke>
    <keystroke id="–"><dec>150</dec><hex>0096</hex></keystroke>
    <keystroke id="—"><dec>151</dec><hex>0097</hex></keystroke>
    <keystroke id="˜"><dec>152</dec><hex>0098</hex></keystroke>
    <keystroke id="™"><dec>153</dec><hex>0099</hex></keystroke>
    <keystroke id="š"><dec>154</dec><hex>009A</hex></keystroke>
    <keystroke id="›"><dec>155</dec><hex>009B</hex></keystroke>
    <keystroke id="œ"><dec>156</dec><hex>009C</hex></keystroke>
    <keystroke id=""><dec>157</dec><hex>009D</hex></keystroke>
    <keystroke id="ž"><dec>158</dec><hex>009E</hex></keystroke>
    <keystroke id="Ÿ"><dec>159</dec><hex>009F</hex></keystroke>
    <keystroke id=" "><dec>160</dec><hex>00A0</hex></keystroke>
    <keystroke id="¡"><dec>161</dec><hex>00A1</hex></keystroke>
    <keystroke id="¢"><dec>162</dec><hex>00A2</hex></keystroke>
    <keystroke id="£"><dec>163</dec><hex>00A3</hex></keystroke>
    <keystroke id="¤"><dec>164</dec><hex>00A4</hex></keystroke>
    <keystroke id="¥"><dec>165</dec><hex>00A5</hex></keystroke>
    <keystroke id="¦"><dec>166</dec><hex>00A6</hex></keystroke>
    <keystroke id="§"><dec>167</dec><hex>00A7</hex></keystroke>
    <keystroke id="¨"><dec>168</dec><hex>00A8</hex></keystroke>
    <keystroke id="©"><dec>169</dec><hex>00A9</hex></keystroke>
    <keystroke id="ª"><dec>170</dec><hex>00AA</hex></keystroke>
    <keystroke id="«"><dec>171</dec><hex>00AB</hex></keystroke>
    <keystroke id="¬"><dec>172</dec><hex>00AC</hex></keystroke>
    <keystroke id="­"><dec>173</dec><hex>00AD</hex></keystroke>
    <keystroke id="®"><dec>174</dec><hex>00AE</hex></keystroke>
    <keystroke id="¯"><dec>175</dec><hex>00AF</hex></keystroke>
    <keystroke id="°"><dec>176</dec><hex>00B0</hex></keystroke>
    <keystroke id="±"><dec>177</dec><hex>00B1</hex></keystroke>
    <keystroke id="²"><dec>178</dec><hex>00B2</hex></keystroke>
    <keystroke id="³"><dec>179</dec><hex>00B3</hex></keystroke>
    <keystroke id="´"><dec>180</dec><hex>00B4</hex></keystroke>
    <keystroke id="µ"><dec>181</dec><hex>00B5</hex></keystroke>
    <keystroke id="¶"><dec>182</dec><hex>00B6</hex></keystroke>
    <keystroke id="·"><dec>183</dec><hex>00B7</hex></keystroke>
    <keystroke id="¸"><dec>184</dec><hex>00B8</hex></keystroke>
    <keystroke id="¹"><dec>185</dec><hex>00B9</hex></keystroke>
    <keystroke id="º"><dec>186</dec><hex>00BA</hex></keystroke>
    <keystroke id="»"><dec>187</dec><hex>00BB</hex></keystroke>
    <keystroke id="¼"><dec>188</dec><hex>00BC</hex></keystroke>
    <keystroke id="½"><dec>189</dec><hex>00BD</hex></keystroke>
    <keystroke id="¾"><dec>190</dec><hex>00BE</hex></keystroke>
    <keystroke id="¿"><dec>191</dec><hex>00BF</hex></keystroke>
    <keystroke id="À"><dec>192</dec><hex>00C0</hex></keystroke>
    <keystroke id="Á"><dec>193</dec><hex>00C1</hex></keystroke>
    <keystroke id="Â"><dec>194</dec><hex>00C2</hex></keystroke>
    <keystroke id="Ã"><dec>195</dec><hex>00C3</hex></keystroke>
    <keystroke id="Ä"><dec>196</dec><hex>00C4</hex></keystroke>
    <keystroke id="Å"><dec>197</dec><hex>00C5</hex></keystroke>
    <keystroke id="Æ"><dec>198</dec><hex>00C6</hex></keystroke>
    <keystroke id="Ç"><dec>199</dec><hex>00C7</hex></keystroke>
    <keystroke id="È"><dec>200</dec><hex>00C8</hex></keystroke>
    <keystroke id="É"><dec>201</dec><hex>00C9</hex></keystroke>
    <keystroke id="Ê"><dec>202</dec><hex>00CA</hex></keystroke>
    <keystroke id="Ë"><dec>203</dec><hex>00CB</hex></keystroke>
    <keystroke id="Ì"><dec>204</dec><hex>00CC</hex></keystroke>
    <keystroke id="Í"><dec>205</dec><hex>00CD</hex></keystroke>
    <keystroke id="Î"><dec>206</dec><hex>00CE</hex></keystroke>
    <keystroke id="Ï"><dec>207</dec><hex>00CF</hex></keystroke>
    <keystroke id="Ð"><dec>208</dec><hex>00D0</hex></keystroke>
    <keystroke id="Ñ"><dec>209</dec><hex>00D1</hex></keystroke>
    <keystroke id="Ò"><dec>210</dec><hex>00D2</hex></keystroke>
    <keystroke id="Ó"><dec>211</dec><hex>00D3</hex></keystroke>
    <keystroke id="Ô"><dec>212</dec><hex>00D4</hex></keystroke>
    <keystroke id="Õ"><dec>213</dec><hex>00D5</hex></keystroke>
    <keystroke id="Ö"><dec>214</dec><hex>00D6</hex></keystroke>
    <keystroke id="×"><dec>215</dec><hex>00D7</hex></keystroke>
    <keystroke id="Ø"><dec>216</dec><hex>00D8</hex></keystroke>
    <keystroke id="Ù"><dec>217</dec><hex>00D9</hex></keystroke>
    <keystroke id="Ú"><dec>218</dec><hex>00DA</hex></keystroke>
    <keystroke id="Û"><dec>219</dec><hex>00DB</hex></keystroke>
    <keystroke id="Ü"><dec>220</dec><hex>00DC</hex></keystroke>
    <keystroke id="Ý"><dec>221</dec><hex>00DD</hex></keystroke>
    <keystroke id="Þ"><dec>222</dec><hex>00DE</hex></keystroke>
    <keystroke id="ß"><dec>223</dec><hex>00DF</hex></keystroke>
    <keystroke id="à"><dec>224</dec><hex>00E0</hex></keystroke>
    <keystroke id="á"><dec>225</dec><hex>00E1</hex></keystroke>
    <keystroke id="â"><dec>226</dec><hex>00E2</hex></keystroke>
    <keystroke id="ã"><dec>227</dec><hex>00E3</hex></keystroke>
    <keystroke id="ä"><dec>228</dec><hex>00E4</hex></keystroke>
    <keystroke id="å"><dec>229</dec><hex>00E5</hex></keystroke>
    <keystroke id="æ"><dec>230</dec><hex>00E6</hex></keystroke>
    <keystroke id="ç"><dec>231</dec><hex>00E7</hex></keystroke>
    <keystroke id="è"><dec>232</dec><hex>00E8</hex></keystroke>
    <keystroke id="é"><dec>233</dec><hex>00E9</hex></keystroke>
    <keystroke id="ê"><dec>234</dec><hex>00EA</hex></keystroke>
    <keystroke id="ë"><dec>235</dec><hex>00EB</hex></keystroke>
    <keystroke id="ì"><dec>236</dec><hex>00EC</hex></keystroke>
    <keystroke id="í"><dec>237</dec><hex>00ED</hex></keystroke>
    <keystroke id="î"><dec>238</dec><hex>00EE</hex></keystroke>
    <keystroke id="ï"><dec>239</dec><hex>00EF</hex></keystroke>
    <keystroke id="ð"><dec>240</dec><hex>00F0</hex></keystroke>
    <keystroke id="ñ"><dec>241</dec><hex>00F1</hex></keystroke>
    <keystroke id="ò"><dec>242</dec><hex>00F2</hex></keystroke>
    <keystroke id="ó"><dec>243</dec><hex>00F3</hex></keystroke>
    <keystroke id="ô"><dec>244</dec><hex>00F4</hex></keystroke>
    <keystroke id="õ"><dec>245</dec><hex>00F5</hex></keystroke>
    <keystroke id="ö"><dec>246</dec><hex>00F6</hex></keystroke>
    <keystroke id="÷"><dec>247</dec><hex>00F7</hex></keystroke>
    <keystroke id="ø"><dec>248</dec><hex>00F8</hex></keystroke>
    <keystroke id="ù"><dec>249</dec><hex>00F9</hex></keystroke>
    <keystroke id="ú"><dec>250</dec><hex>00FA</hex></keystroke>
    <keystroke id="û"><dec>251</dec><hex>00FB</hex></keystroke>
    <keystroke id="ü"><dec>252</dec><hex>00FC</hex></keystroke>
    <keystroke id="ý"><dec>253</dec><hex>00FD</hex></keystroke>
    <keystroke id="þ"><dec>254</dec><hex>00FE</hex></keystroke>
    <keystroke id="ÿ"><dec>255</dec><hex>00FF</hex></keystroke>
    <keystroke id="Œ"><dec>338</dec><hex>0152</hex></keystroke>
    <keystroke id="œ"><dec>339</dec><hex>0153</hex></keystroke>
    <keystroke id="Ÿ"><dec>376</dec><hex>0178</hex></keystroke>
    <keystroke id="Ÿ"><dec>376</dec><hex>0178</hex></keystroke>
    <keystroke id="ˆ"><dec>710</dec><hex>02C6</hex></keystroke>
    <keystroke id="˚"><dec>730</dec><hex>02DA</hex></keystroke>
    <keystroke id="˜"><dec>732</dec><hex>02DC</hex></keystroke>
    <keystroke id="Ω"><dec>937</dec><hex>03A9</hex></keystroke>
    <keystroke id="•"><dec>8226</dec><hex>2022</hex></keystroke>
    <keystroke id="‰"><dec>8240</dec><hex>2030</hex></keystroke>
    <keystroke id="™"><dec>8482</dec><hex>2122</hex></keystroke>
    <keystroke id="∂"><dec>8706</dec><hex>2202</hex></keystroke>
    <keystroke id="√"><dec>8730</dec><hex>221A</hex></keystroke>
    <keystroke id="∞"><dec>8734</dec><hex>221E</hex></keystroke>
    <keystroke id="∫"><dec>8747</dec><hex>222B</hex></keystroke>
    <keystroke id="◊"><dec>9674</dec><hex>25CA</hex></keystroke>
</strokes>    
<!-- 
    <keystroke id="Ä"><dec>128</dec><hex>0080</hex></keystroke>
    <keystroke id="Å"><dec>129</dec><hex>0081</hex></keystroke>
    <keystroke id="Ç"><dec>130</dec><hex>0082</hex></keystroke>
    <keystroke id="É"><dec>131</dec><hex>0083</hex></keystroke>
    <keystroke id="Ñ"><dec>132</dec><hex>0084</hex></keystroke>
    <keystroke id="Ö"><dec>133</dec><hex>0085</hex></keystroke>
    <keystroke id="Ü"><dec>134</dec><hex>0086</hex></keystroke>
    <keystroke id="á"><dec>135</dec><hex>0087</hex></keystroke>
    <keystroke id="à"><dec>136</dec><hex>0088</hex></keystroke>
    <keystroke id="â"><dec>137</dec><hex>0089</hex></keystroke>
    <keystroke id="ä"><dec>138</dec><hex>008A</hex></keystroke>
    <keystroke id="ã"><dec>139</dec><hex>008B</hex></keystroke>
    <keystroke id="å"><dec>140</dec><hex>008C</hex></keystroke>
    <keystroke id="ç"><dec>141</dec><hex>008D</hex></keystroke>
    <keystroke id="é"><dec>142</dec><hex>008E</hex></keystroke>
    <keystroke id="è"><dec>143</dec><hex>008F</hex></keystroke>
    <keystroke id="ê"><dec>144</dec><hex>0090</hex></keystroke>
    <keystroke id="ë"><dec>145</dec><hex>0091</hex></keystroke>
    <keystroke id="í"><dec>146</dec><hex>0092</hex></keystroke>
    <keystroke id="ì"><dec>147</dec><hex>0093</hex></keystroke>
    <keystroke id="î"><dec>148</dec><hex>0094</hex></keystroke>
    <keystroke id="ï"><dec>149</dec><hex>0095</hex></keystroke>
    <keystroke id="ñ"><dec>150</dec><hex>0096</hex></keystroke>
    <keystroke id="ó"><dec>151</dec><hex>0097</hex></keystroke>
    <keystroke id="ò"><dec>152</dec><hex>0098</hex></keystroke>
    <keystroke id="ô"><dec>153</dec><hex>0099</hex></keystroke>
    <keystroke id="ö"><dec>154</dec><hex>009A</hex></keystroke>
    <keystroke id="õ"><dec>155</dec><hex>009B</hex></keystroke>
    <keystroke id="ú"><dec>156</dec><hex>009C</hex></keystroke>
    <keystroke id="ù"><dec>157</dec><hex>009D</hex></keystroke>
    <keystroke id="û"><dec>158</dec><hex>009E</hex></keystroke>
    <keystroke id="ü"><dec>159</dec><hex>009F</hex></keystroke>
    <keystroke id="†"><dec>160</dec><hex>00A0</hex></keystroke>
    <keystroke id="°"><dec>161</dec><hex>00A1</hex></keystroke>
    <keystroke id="¢"><dec>162</dec><hex>00A2</hex></keystroke>
    <keystroke id="£"><dec>163</dec><hex>00A3</hex></keystroke>
    <keystroke id="§"><dec>164</dec><hex>00A4</hex></keystroke>
    <keystroke id="•"><dec>165</dec><hex>00A5</hex></keystroke>
    <keystroke id="¶"><dec>166</dec><hex>00A6</hex></keystroke>
    <keystroke id="ß"><dec>167</dec><hex>00A7</hex></keystroke>
    <keystroke id="®"><dec>168</dec><hex>00A8</hex></keystroke>
    <keystroke id="©"><dec>169</dec><hex>00A9</hex></keystroke>
    <keystroke id="™"><dec>170</dec><hex>00AA</hex></keystroke>
    <keystroke id="´"><dec>171</dec><hex>00AB</hex></keystroke>
    <keystroke id="¨"><dec>172</dec><hex>00AC</hex></keystroke>
    <keystroke id="≠"><dec>173</dec><hex>00AD</hex></keystroke>
    <keystroke id="Æ"><dec>174</dec><hex>00AE</hex></keystroke>
    <keystroke id="Ø"><dec>175</dec><hex>00AF</hex></keystroke>
    <keystroke id="∞"><dec>176</dec><hex>00B0</hex></keystroke>
    <keystroke id="±"><dec>177</dec><hex>00B1</hex></keystroke>
    <keystroke id="≤"><dec>178</dec><hex>00B2</hex></keystroke>
    <keystroke id="≥"><dec>179</dec><hex>00B3</hex></keystroke>
    <keystroke id="¥"><dec>180</dec><hex>00B4</hex></keystroke>
    <keystroke id="µ"><dec>181</dec><hex>00B5</hex></keystroke>
    <keystroke id="∂"><dec>182</dec><hex>00B6</hex></keystroke>
    <keystroke id="∑"><dec>183</dec><hex>00B7</hex></keystroke>
    <keystroke id="∏"><dec>184</dec><hex>00B8</hex></keystroke>
    <keystroke id="π"><dec>185</dec><hex>00B9</hex></keystroke>
    <keystroke id="∫"><dec>186</dec><hex>00BA</hex></keystroke>
    <keystroke id="ª"><dec>187</dec><hex>00BB</hex></keystroke>
    <keystroke id="º"><dec>188</dec><hex>00BC</hex></keystroke>
    <keystroke id="Ω"><dec>189</dec><hex>00BD</hex></keystroke>
    <keystroke id="æ"><dec>190</dec><hex>00BE</hex></keystroke>
    <keystroke id="ø"><dec>191</dec><hex>00BF</hex></keystroke>
    <keystroke id="¿"><dec>192</dec><hex>00C0</hex></keystroke>
    <keystroke id="¡"><dec>193</dec><hex>00C1</hex></keystroke>
    <keystroke id="¬"><dec>194</dec><hex>00C2</hex></keystroke>
    <keystroke id="√"><dec>195</dec><hex>00C3</hex></keystroke>
    <keystroke id="ƒ"><dec>196</dec><hex>00C4</hex></keystroke>
    <keystroke id="≈"><dec>197</dec><hex>00C5</hex></keystroke>
    <keystroke id="∆"><dec>198</dec><hex>00C6</hex></keystroke>
    <keystroke id="«"><dec>199</dec><hex>00C7</hex></keystroke>
    <keystroke id="»"><dec>200</dec><hex>00C8</hex></keystroke>
    <keystroke id="…"><dec>201</dec><hex>00C9</hex></keystroke>
    <keystroke id=" "><dec>202</dec><hex>00CA</hex></keystroke>
    <keystroke id="À"><dec>203</dec><hex>00CB</hex></keystroke>
    <keystroke id="Ã"><dec>204</dec><hex>00CC</hex></keystroke>
    <keystroke id="Õ"><dec>205</dec><hex>00CD</hex></keystroke>
    <keystroke id="Œ"><dec>206</dec><hex>00CE</hex></keystroke>
    <keystroke id="œ"><dec>207</dec><hex>00CF</hex></keystroke>
    <keystroke id="–"><dec>208</dec><hex>00D0</hex></keystroke>
    <keystroke id="—"><dec>209</dec><hex>00D1</hex></keystroke>
    <keystroke id="“"><dec>210</dec><hex>00D2</hex></keystroke>
    <keystroke id="”"><dec>211</dec><hex>00D3</hex></keystroke>
    <keystroke id="‘"><dec>212</dec><hex>00D4</hex></keystroke>
    <keystroke id="’"><dec>213</dec><hex>00D5</hex></keystroke>
    <keystroke id="÷"><dec>214</dec><hex>00D6</hex></keystroke>
    <keystroke id="◊"><dec>215</dec><hex>00D7</hex></keystroke>
    <keystroke id="ÿ"><dec>216</dec><hex>00D8</hex></keystroke>
    <keystroke id="Ÿ"><dec>217</dec><hex>00D9</hex></keystroke>
    <keystroke id="⁄"><dec>218</dec><hex>00DA</hex></keystroke>
    <keystroke id="€"><dec>219</dec><hex>00DB</hex></keystroke>
    <keystroke id="‹"><dec>220</dec><hex>00DC</hex></keystroke>
    <keystroke id="›"><dec>221</dec><hex>00DD</hex></keystroke>
    <keystroke id="ﬁ"><dec>222</dec><hex>00DE</hex></keystroke>
    <keystroke id="ﬂ"><dec>223</dec><hex>00DF</hex></keystroke>
    <keystroke id="‡"><dec>224</dec><hex>00E0</hex></keystroke>
    <keystroke id="·"><dec>225</dec><hex>00E1</hex></keystroke>
    <keystroke id="‚"><dec>226</dec><hex>00E2</hex></keystroke>
    <keystroke id="„"><dec>227</dec><hex>00E3</hex></keystroke>
    <keystroke id="‰"><dec>228</dec><hex>00E4</hex></keystroke>
    <keystroke id="Â"><dec>229</dec><hex>00E5</hex></keystroke>
    <keystroke id="Ê"><dec>230</dec><hex>00E6</hex></keystroke>
    <keystroke id="Á"><dec>231</dec><hex>00E7</hex></keystroke>
    <keystroke id="Ë"><dec>232</dec><hex>00E8</hex></keystroke>
    <keystroke id="È"><dec>233</dec><hex>00E9</hex></keystroke>
    <keystroke id="Í"><dec>234</dec><hex>00EA</hex></keystroke>
    <keystroke id="Î"><dec>235</dec><hex>00EB</hex></keystroke>
    <keystroke id="Ï"><dec>236</dec><hex>00EC</hex></keystroke>
    <keystroke id="Ì"><dec>237</dec><hex>00ED</hex></keystroke>
    <keystroke id="Ó"><dec>238</dec><hex>00EE</hex></keystroke>
    <keystroke id="Ô"><dec>239</dec><hex>00EF</hex></keystroke>
    <keystroke id=""><dec>240</dec><hex>00F0</hex></keystroke>
    <keystroke id="Ò"><dec>241</dec><hex>00F1</hex></keystroke>
    <keystroke id="Ú"><dec>242</dec><hex>00F2</hex></keystroke>
    <keystroke id="Û"><dec>243</dec><hex>00F3</hex></keystroke>
    <keystroke id="Ù"><dec>244</dec><hex>00F4</hex></keystroke>
    <keystroke id="ı"><dec>245</dec><hex>00F5</hex></keystroke>
    <keystroke id="ˆ"><dec>246</dec><hex>00F6</hex></keystroke>
    <keystroke id="˜"><dec>247</dec><hex>00F7</hex></keystroke>
    <keystroke id="¯"><dec>248</dec><hex>00F8</hex></keystroke>
    <keystroke id="˘"><dec>249</dec><hex>00F9</hex></keystroke>
    <keystroke id="˙"><dec>250</dec><hex>00FA</hex></keystroke>
    <keystroke id="˚"><dec>251</dec><hex>00FB</hex></keystroke>
    <keystroke id="¸"><dec>252</dec><hex>00FC</hex></keystroke>
    <keystroke id="˝"><dec>253</dec><hex>00FD</hex></keystroke>
    <keystroke id="˛"><dec>254</dec><hex>00FE</hex></keystroke>
    <keystroke id="ˇ"><dec>255</dec><hex>00FF</hex></keystroke>
-->